version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: ./api/docker/Dockerfile
    image: alsbury/php-app:latest
    networks:
      - appnet
    # volumes:
    #   - .:/var/www/html
    ports:
      - "${APP_PORT:-127.0.0.1:80}:80"
    working_dir: /var/www/html
  cache:
    image: redis:alpine
    networks:
      - appnet
    volumes:
      - cachedata:/data
  node:
    build:
      context: ./ui/docker
      dockerfile: Dockerfile
    image: shippingdocker/node:latest
    networks:
      - appnet
    volumes:
      - .:/opt
    working_dir: /opt
    command: echo hi
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
