version: '3.3'
services:
  app:
    volumes:
      - .:/var/www/html
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
    ports:
      - "${DB_PORT:-127.0.0.1:3306}:80"
    networks:
      - appnet
    volumes:
      - dbdata:/var/lib/mysql
